# Generated by Django 2.2.6 on 2019-10-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provincia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('provincia_id', models.IntegerField()),
            ],
            options={
                'db_table': 'ciudades',
                'managed': False,
            },
        ),
    ]
